spring:
  application:
    name: core-service
  datasource:
    url: jdbc:mysql://${SYSTEM_DB_HOST}:3306/microweaver
    username: root
    password: ${SYSTEM_DB_SECRET}
    testWhileIdle: true
    validationQuery: SELECT 1 
    tomcat:
      max-active: 50
      max-idle: 20
      max-wait: 20000
      min-idle: 15
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update      
      format_sql: true
      
info:
    enabled: true
    sensitive: false
    app:
      name: Core Service
      version: 0.0.1-SNAPSHOT
        
endpoints:
  enabled: true
   
server:
  port: 9180
  servletPath: /
 
management:
  security:
    enabled: false
  
eureka:
  instance:
    hostname: ${MICROSERVICE_SERVICE_NAME}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SYSTEM_REGISTRY_DEFAULT_ZONE}
    healthcheck:
      enabled: true
    
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json
        
application:
  system:
    loadBootstrapServicesToDb: true
  kubernetes:
    url: https://kubernetes.default:443
    authTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token
    probes:
      initialDelaySeconds: 120
      failureThreshold: 10