apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microweaver-sidecar-service
  name: microweaver-sidecar-service
  namespace: microweaver-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microweaver-sidecar-service
  template:
    metadata:
      labels:
        app: microweaver-sidecar-service
      name: microweaver-sidecar-service
      namespace: microweaver-system
    spec:
      containers:
      - name: microweaver-sidecar-service
        image: 192.168.57.150:5000/microweaver/microweaver-sidecar-service:0.0.1-SNAPSHOT
        resources:
          limits:
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http-main          
          initialDelaySeconds: 120
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http-main
          initialDelaySeconds: 120
          failureThreshold: 10
        ports:
        - name: http-main
          containerPort: 9178
        - name: http-sidecar
          containerPort: 7000
        imagePullPolicy: Always
        env:
        - name: MICROSERVICE_SERVICE_NAME
          value: microweaver-sidecar-service
        - name: EUREKA_SERVICE_NAME_01
          value: microweaver-registry-service-01
        - name: EUREKA_SERVICE_NAME_02
          value: microweaver-registry-service-02