apiVersion: v1
kind: Service
metadata:
  labels:
    app: microweaver-sidecar-service
  name: microweaver-sidecar-service
  namespace: microweaver-system
spec:
  type: NodePort  
  ports:
  - name: http-main
    port: 9178
    targetPort: 9178
    protocol: TCP
  - name: http-sidecar
    port: 7000
    targetPort: 7000
    protocol: TCP
  selector:
    app: microweaver-sidecar-service