# 
# Configuration to deploy service
#
# - microweaver-sidecar-service
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microweaver-sidecar-service
  name: microweaver-sidecar-service
  namespace: microweaver-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microweaver-sidecar-service
  template:
    metadata:
      labels:
        app: microweaver-sidecar-service
      name: microweaver-sidecar-service
      namespace: microweaver-system
    spec:
      containers:
      - name: microweaver-sidecar-service
        image: 10.228.240.149:5000/microweaver/microweaver-sidecar-service:0.0.1-SNAPSHOT
        livenessProbe:
          httpGet:
            path: /health
            port: http-sidecar          
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http-sidecar
          initialDelaySeconds: 20
        ports:
        - name: http-sidecar
          containerPort: 9178
        - name: http-flask
          containerPort: 7000
        imagePullPolicy: Always
        env:
        - name: MICROSERVICE_SERVICE_NAME
          value: microweaver-sidecar-service
        - name: EUREKA_SERVICE_NAME_01
          value: microweaver-registry-service-01
        - name: EUREKA_SERVICE_NAME_02
          value: microweaver-registry-service-02
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microweaver-sidecar-service
  name: microweaver-sidecar-service
  namespace: microweaver-system
spec:
  type: NodePort  
  ports:
  - name: http-sidecar
    port: 9178
    targetPort: 9178
    protocol: TCP
  - name: http-flask
    port: 7000
    targetPort: 7000
    protocol: TCP
  selector:
    app: microweaver-sidecar-service