apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microweaver-registry-service-02  
  namespace: microweaver-system
  labels:
    app: microweaver-registry-service-02
spec:
  replicas: 1
  template:
    metadata:
      name: microweaver-registry-service-02
      namespace: microweaver-system
      labels:
        app: microweaver-registry-service-02
    spec:
      containers:
      - name: microweaver-registry-service-02
        image: 192.168.57.150:5000/microweaver/microweaver-registry-service:0.0.1-SNAPSHOT
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http-main
          initialDelaySeconds: 120
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http-main
          initialDelaySeconds: 120
          failureThreshold: 10
        ports:
        - name: http-main
          containerPort: 9161
        imagePullPolicy: Always
        env:
        - name: MICROSERVICE_SERVICE_NAME
          value: microweaver-registry-service-02
        - name: SYSTEM_REGISTRY_DEFAULT_ZONE
          value: http://microweaver-registry-service-01:9161/eureka/,http://microweaver-registry-service-02:9161/eureka/