apiVersion: v1
kind: Service
metadata:
  name: microweaver-registry-service-01
  namespace: microweaver-system
  labels:
    app: microweaver-registry-service-01
spec:
  ports:
  - name: http
    port: 9161
    protocol: TCP
  selector:
    app: microweaver-registry-service-01