FROM centos:centos7.3.1611
RUN yum install -y epel-release
RUN yum install -y java-1.8.0-openjdk
RUN yum install -y bind-utils
RUN yum install -y wget
RUN yum install -y telnet
RUN yum install -y python
RUN yum install -y python-pip
RUN yum install -y supervisor
RUN yum install -y mysql
RUN pip install -U pip
RUN pip install kubernetes
MAINTAINER Anish Sneh email: anishsneh@anishsneh.com