spring:
  application:
    name: admin-service
    
info:
    enabled: true
    sensitive: false
    app:
      name: Admin Service
      version: 0.0.1-SNAPSHOT
    
server:
  port: 9190
  
management:
  security:
    enabled: false

eureka:
  instance:
    hostname: ${MICROSERVICE_SERVICE_NAME}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_NAME_01}:9161/eureka/,http://${EUREKA_SERVICE_NAME_02}:9161/eureka/
    healthcheck:
      enabled: true