apiVersion: v1
kind: Service
metadata:
  labels:
    app: microweaver-admin-service
  name: microweaver-admin-service
  namespace: microweaver-system
spec:
  type: NodePort  
  ports:
  - name: http
    port: 9190
    nodePort: 30090
    targetPort: 9190
    protocol: TCP
  selector:
    app: microweaver-admin-service