ip_address = "192.168.57.150"
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network :private_network, ip: ip_address
  config.vm.provider :virtualbox do |vb|
    vb.name = "kubernetes-all"
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
  SHELL
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end