# 
# Configuration to deploy service
#
# - microweaver-core-service
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microweaver-core-service
  name: microweaver-core-service
  namespace: microweaver-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microweaver-core-service
  template:
    metadata:
      labels:
        app: microweaver-core-service
      name: microweaver-core-service
      namespace: microweaver-system
    spec:
      containers:
      - name: microweaver-core-service
        image: 192.168.57.150:5000/microweaver/microweaver-core-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9180
        imagePullPolicy: Always
        env:
        - name: MICROSERVICE_SERVICE_NAME
          value: microweaver-core-service
        - name: SYSTEM_REGISTRY_DEFAULT_ZONE
          value: http://microweaver-registry-service-01:9161/eureka/,http://microweaver-registry-service-02:9161/eureka/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microweaver-core-service
  name: microweaver-core-service
  namespace: microweaver-system
spec:
  type: NodePort  
  ports:
  - name: http
    port: 9180
    targetPort: 9180
    protocol: TCP
  selector:
    app: microweaver-core-service