apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
      name: apache
      namespace: kube-system
    spec:
      containers:
      - name: apache
        image: centos/httpd
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
  namespace: microweaver-system
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apache