apiVersion: v1
kind: Service
metadata:
  labels:
    app: microweaver-core-service
  name: microweaver-core-service
  namespace: microweaver-system
spec:
  type: NodePort  
  ports:
  - name: http
    port: 9180
    targetPort: 9180
    protocol: TCP
  selector:
    app: microweaver-core-service