apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microweaver-core-service
  name: microweaver-core-service
  namespace: microweaver-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microweaver-core-service
  template:
    metadata:
      labels:
        app: microweaver-core-service
      name: microweaver-core-service
      namespace: microweaver-system
    spec:
      containers:
      - name: microweaver-core-service
        image: 10.228.240.149:5000/microweaver/microweaver-core-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9180
        imagePullPolicy: Always
        env:
        - name: MICROSERVICE_SERVICE_NAME
          value: microweaver-core-service
        - name: EUREKA_SERVICE_NAME_01
          value: microweaver-registry-service-01
        - name: EUREKA_SERVICE_NAME_02
          value: microweaver-registry-service-02