# 
# Configuration to deploy service
#
# - microweaver-gateway-service
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microweaver-gateway-service
  name: microweaver-gateway-service
  namespace: microweaver-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microweaver-gateway-service
  template:
    metadata:
      labels:
        app: microweaver-gateway-service
      name: microweaver-gateway-service
      namespace: microweaver-system
    spec:
      containers:
      - name: microweaver-gateway-service
        image: 192.168.57.150:5000/microweaver/microweaver-gateway-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9165
        imagePullPolicy: Always
        env:
        - name: MICROSERVICE_SERVICE_NAME
          value: microweaver-gateway-service
        - name: EUREKA_SERVICE_NAME_01
          value: microweaver-registry-service-01
        - name: EUREKA_SERVICE_NAME_02
          value: microweaver-registry-service-02
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microweaver-gateway-service
  name: microweaver-gateway-service
  namespace: microweaver-system
spec:
  type: NodePort  
  ports:
  - name: http
    port: 9165
    targetPort: 9165
    protocol: TCP
  selector:
    app: microweaver-gateway-service