#
# MUST enable MySQL password and allow login from any host
#
---
kind: Service
apiVersion: v1
metadata:
  name: microweaver-core-database
  namespace: microweaver-system
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: microweaver-core-database
  namespace: microweaver-system
subsets:
- addresses:
  - ip: 192.168.57.150
  ports:
  - port: 3306