spring:
  application:
    name: gateway-service
    
info:
    enabled: true
    sensitive: false
    app:
      name: Gateway Service
      version: 0.0.1-SNAPSHOT
    
server:
  port: 9165
  
management:
  security:
    enabled: false

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 3000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
          
eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: false
      fetchRegistry: false
      
zuul:
  prefix: /api